### PR TITLE
Add testimonial marquee

### PR DESCRIPTION
**Pull request by DanGould**
Social proof above the fold

### CODE REVIEW

**Comment by DanGould** [comment]
@thebrandonlucas Alex Lewin fixed the heck out of my training wheels tailwind. However, the styling still makes this header a bit cramped. I'd love to have the tesimonials small and above the fold, but I'm not sure how to balance the elements. Perhaps you could help expand on my most previoius "Size HeaderContent.. " commit so that the landing screen above the fold can be a thing of beauty

**Comment by thebrandonlucas** [comment]
@DanGould This is a great idea. I updated the CSS to make the quotes look more like quotes, be a bit smaller, and give the title some space, let me know what you think.

Also, I would love it if you had links to the sources of these quotes, so that people could click on these and see that the testimonials are legitimate.
Screenshot 2024-07-29 at 9 38 20 AM

**Comment by DanGould** [comment]
Sources are all here, https://github.com/orgs/payjoin/projects/1/views/1?pane=issue&itemId=25222816

Some of them are from now-deleted twitter accounts, so I'd rather just leave them as plain text. Someone would complain if they're attributed so I think our reputation and the fact that we asked explicitly makes posting without links my preference for now, at least. It also lets us use testimonials that aren't explicit public tweets but things relayed directly to us.

**Comment by thebrandonlucas** [comment]
@DanGould works for me! Let me know how you want to proceed with this one. I approved it and am good with the changes. If you want me to change anything else let me know.

**Review by thebrandonlucas — APPROVED** [review]

**Pull request merged**
